# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='refnum',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
