# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('e', 'Expense'), ('i', 'Income')], max_length=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsa.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('0', 'CHECKING'), ('S', 'SAVINGS'), ('C', 'CCARD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='refnum',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebsa.Category'),
            preserve_default=False,
        ),
    ]
