# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsa', '0002_auto_20160105_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('0', 'CHECKING'), ('S', 'SAVINGS'), ('C', 'CCARD')], max_length=1),
        ),
    ]
