# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebsa', '0002_auto_20160216_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ebsa.Category'),
        ),
    ]
