# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebsa', '0004_auto_20160216_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebsa.Category'),
        ),
    ]
